### ISSUE TITLE
Not all banking requests visible (or wrong counter)

### ISSUE THREAD

**Issue by HermanRonk** [dssecret/tornium#82]
![tornium](https://user-images.githubusercontent.com/2781343/147547576-6132d3b3-1e63-415d-a202-930fd4267768.png)

There is something wrong with the counter/pagination,.

**Comment by dssecret** [comment]
I believe this is an issue with the recordsFiltered and recordsTotal passed to DataTables. Will fix soon.

**Comment by dssecret** [comment]
Fixed and production has been updated. Thanks!
